version: 0.2
phases:
  install:
    commands:
      - echo "Installing Helm"
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  pre_build:
    commands:
      - export IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 6)
      - export ENV=prod
      - echo "Image Tag - $IMAGE_TAG"
      - echo "Installing Docker"
      - curl -fsSL https://get.docker.com -o get-docker.sh && sh ./get-docker.sh
  build:
    commands:
      - printenv > .env
      - aws secretsmanager get-secret-value --secret-id lets-connect-landing-ui-prod --region ap-southeast-1 | jq -r '.SecretString' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> .env
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker build -t $REPOSITORY_URI:${IMAGE_TAG} .
      - docker push $REPOSITORY_URI:${IMAGE_TAG}
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION --role-arn $ROLE_ARN
      - helm upgrade --install $HELM_RELEASE_NAME chart/lets-connect -n $ENV -f chart/lets-connect/values-$ENV.yaml --set image.repository=$REPOSITORY_URI --set image.tag=$IMAGE_TAG --create-namespace --wait
