{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: "20%"
     maxSurge: "20%"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/release: {{ $.Release.Name }}
    spec:
      serviceAccountName: {{ $.Release.Name }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $.Release.Name }}-spc
      containers:
        - name: {{ $.Release.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $.Values.service.targetPort }}
              protocol: TCP
          command:
          - /bin/bash
          - -c
          - jq -r 'to_entries | .[] | "\(.key)=\"\(.value)\""' /mnt/secrets/lets-connect-landing-ui-{{ $.Values.environment }} > .env && {{ .command }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-configmap
          # livenessProbe:
          #   initialDelaySeconds: 30
          #   httpGet:
          #     path: /health
          #     port: {{ $.Values.service.targetPort }}
          #   periodSeconds: 20
          #   timeoutSeconds: 10
          # readinessProbe:
          #   initialDelaySeconds: 30
          #   httpGet:
          #     path: /health
          #     port: {{ $.Values.service.targetPort }}
          #   periodSeconds: 20
          #   timeoutSeconds: 10
          resources:
{{ toYaml .resources | indent 12 }}
    {{- with $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
