apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Release.Name }}-spc
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: lets-connect-landing-ui-{{ $.Values.environment }}
        objectType: "secretsmanager"
